language: rust
rust:
    - beta
    - nightly
os:
    - linux
    - osx
env:
  global:
    - secure: kd+Q+IWrHUZK+BwwEh37IiR7B76yyvfjAB3Gx6roshKyAk2KmduoyLGv6v902gbLAtt/8JtPMBHZdKbMv7A1eKBsCOF/rMz1rHziuTbnFwfnx6UN+jalZZRIYmn20M7I1UfvhcvWXqvcrpo84NbhOYlXMmvI+X6HZ2rSIsYta6E=
    - VERBOSE: 1
script:
    - make travis_script
notifications:
    irc:
        channels:
            - "chat.freenode.net#libpnet"
        use_notice: true
